export const CHANGE_HOME_LIST = 'home/CHANGE_HOME_LIST';
export const CHANGE_HOME_MORE_LIST = 'home/CHANGE_HOME_MORE_LIST';
export const CHANGE_AURHORS_LIST = 'home/CHANGE_AURHORS_LIST';
export const HANDLE_SWITCH_CLICK = 'home/HANDLE_SWITCH_CLICK';
